version: '3.4'

services:

  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: exit 0
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: 'bullets'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
        - ./bullet-tracker-api/server/bulletdb.sql:/docker-entrypoint-initdb.d/bulletdb.sql

  bullettrackerapi:
      image: dfarris97/project1:bullettrackerapi
      build:
        context: bullet-tracker-api
        dockerfile: ./Dockerfile
      healthcheck:
        test: exit 0
      command: npm start
      environment:
        - DATABASE_URL=postgres://admin:admin@db
        - NODE_ENV=test
      depends_on: 
        db:
          condition: service_healthy
      links:
        - db
      ports:
        - 3001:3001

  bullettrackerreactapp:
      image: dfarris97/project1:bullettrackerreactapp
      build:
        context: bullet-tracker-react-app
        dockerfile: ./Dockerfile
      command: npm start
      depends_on: 
        bullettrackerapi:
          condition: service_healthy
      ports:
        - 3002:3002

