version: '3.4'

services:

  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: exit 0
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: 'bullets'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
        - ./bullet-tracker-api/server/init1.sql:/docker-entrypoint-initdb.d/init1.sql

  bullettrackerapi:
      image: bullettrackerapi
      build:
        context: bullet-tracker-api
        dockerfile: ./Dockerfile
      healthcheck:
        test: exit 0
      command: npm start
      environment:
        - DATABASE_URL=postgres://admin:admin@db
        - NODE_ENV=test
      depends_on: 
        db:
          condition: service_healthy
      links:
        - db
      ports:
        - 3001:3001

