version: '3.4'

services:

  db:
    image: postgres
    healthcheck:
      test: exit 0
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_DB=bullets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1967
    volumes:
        - ./bullet-tracker-api/server/init.sql:/docker-entrypoint-initdb.d/init.sql

  bullettrackerapi:
    image: bullettrackerapi
    build:
      context: bullet-tracker-api
      dockerfile: ./Dockerfile
    healthcheck:
      test: exit 0
    command: npm start
    environment:
      - DATABASE_URL=postgres://postgres:1967@localhose:5432/bullets
      - NODE_ENV=test
    depends_on: 
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - 3001:3001

  bullettrackerreactapp:
    image: bullettrackerreactapp
    build:
      context: bullet-tracker-react-app
      dockerfile: ./Dockerfile
    command: npm start
    environment: 
      - DATABASE_URL=postgres://postgres:1967@localhose:5432/bullets
      - NODE_ENV=test
    depends_on: 
      bullettrackerapi:
        condition: service_healthy
    ports:
      - 3002:3002
